name: novopharma
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+16

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this
    sdk: flutter         # Add this
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.4.0
  image_picker: '>=1.1.2'
  mobile_scanner: ^7.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  http: ^1.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.5+1
  firebase_auth: ^6.0.1
  intl: ^0.20.2
  flutter_gen: ^5.11.0
  collection: ^1.19.1
  cloud_functions: ^6.0.1
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^17.2.3
  timeago: ^3.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.1
  video_player: ^2.8.6
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  image_cropper: ^8.0.2
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  introduction_screen: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true   # iOS App Store

flutter:
  generate: true # Add this
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/introductionScreen/
    - assets/flags/
    - assets/logo/

flutter_native_splash:
  color: "#3A39EE"
  image: assets/logo/splashLogo.png
  
  # Android 12+ parameters
  android_12:
    color: "#3A39EE"
    image: assets/logo/splashLogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
